//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int idCliente { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public Nullable<int> idProduto { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
